// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BusinessLicenses
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("license_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long LicenseId { get; set; }

        [JsonProperty("account_number")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long AccountNumber { get; set; }

        [JsonProperty("site_number")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long SiteNumber { get; set; }

        [JsonProperty("legal_name")]
        public string LegalName { get; set; }

        [JsonProperty("doing_business_as_name")]
        public string DoingBusinessAsName { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("zip_code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ZipCode { get; set; }

        [JsonProperty("ward")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Ward { get; set; }

        [JsonProperty("precinct")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Precinct { get; set; }

        [JsonProperty("ward_precinct")]
        public string WardPrecinct { get; set; }

        [JsonProperty("police_district")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PoliceDistrict { get; set; }

        [JsonProperty("license_code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long LicenseCode { get; set; }

        [JsonProperty("license_description")]
        public string LicenseDescription { get; set; }

        [JsonProperty("business_activity_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long BusinessActivityId { get; set; }

        [JsonProperty("business_activity")]
        public string BusinessActivity { get; set; }

        [JsonProperty("license_number")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long LicenseNumber { get; set; }

        [JsonProperty("application_type")]
        public string ApplicationType { get; set; }

        [JsonProperty("application_requirements_complete")]
        public DateTimeOffset ApplicationRequirementsComplete { get; set; }

        [JsonProperty("payment_date")]
        public DateTimeOffset PaymentDate { get; set; }

        [JsonProperty("conditional_approval")]
        public string ConditionalApproval { get; set; }

        [JsonProperty("license_start_date")]
        public DateTimeOffset LicenseStartDate { get; set; }

        [JsonProperty("expiration_date")]
        public DateTimeOffset ExpirationDate { get; set; }

        [JsonProperty("license_approved_for_issuance")]
        public DateTimeOffset LicenseApprovedForIssuance { get; set; }

        [JsonProperty("date_issued")]
        public DateTimeOffset DateIssued { get; set; }

        [JsonProperty("license_status")]
        public string LicenseStatus { get; set; }

        [JsonProperty("ssa")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Ssa { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty(":@computed_region_vrxf_vc4k")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionVrxfVc4K { get; set; }

        [JsonProperty(":@computed_region_awaf_s7ux")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionAwafS7Ux { get; set; }

        [JsonProperty(":@computed_region_6mkv_f3dw")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegion6MkvF3Dw { get; set; }

        [JsonProperty(":@computed_region_bdys_3d7i")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionBdys3D7I { get; set; }

        [JsonProperty(":@computed_region_43wa_7qmu")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegion43Wa7Qmu { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("human_address")]
        public string HumanAddress { get; set; }
    }

    public partial class BusinessLicenses
    {
        public static BusinessLicenses[] FromJson(string json) => JsonConvert.DeserializeObject<BusinessLicenses[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BusinessLicenses[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
